<#
    xcom_publish.ps1 - turn the swept library into a usable asset folder.

    The bulk sweep and the material pass both write into scratch that a clean
    can delete. This moves the finished library somewhere the prototype can
    load from, verifies it is self-consistent, and drops in the manifests and
    a README.

        .\tools\xcom2\xcom_publish.ps1                       # move to assets/xcom_library
        .\tools\xcom2\xcom_publish.ps1 -Copy                 # keep the scratch copy too
        .\tools\xcom2\xcom_publish.ps1 -Target D:\xcom_assets

    Nothing here re-extracts. Rebuild the source with:
        .\tools\xcom2\xcom_bulk.ps1
        .\tools\xcom2\xcom_materials.ps1 -WriteMtl -PatchObj
#>
[CmdletBinding()]
param(
    [string]$Target,
    [switch]$Copy,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$src = Join-Path $repo 'xcom_extracted\models'
if (-not $Target) { $Target = Join-Path $repo 'assets\xcom_library' }

if (-not (Test-Path -LiteralPath $src)) {
    throw "No library at $src. Run .\tools\xcom2\xcom_bulk.ps1 first."
}
if ((Test-Path -LiteralPath $Target) -and -not $Force) {
    throw "$Target already exists. Pass -Force to replace it."
}

# ------------------------------------------------------------- sanity first
$objs = @(Get-ChildItem $src -Recurse -File -Filter *.obj)
$pngs = @(Get-ChildItem $src -Recurse -File -Filter *.png)
$mtls = @(Get-ChildItem $src -Recurse -File -Filter *.mtl)
Write-Host ("source: {0} meshes, {1} textures, {2} material files" -f $objs.Count, $pngs.Count, $mtls.Count)
if ($mtls.Count -eq 0) {
    Write-Warning "No .mtl files - run .\tools\xcom2\xcom_materials.ps1 -WriteMtl -PatchObj first, or meshes will publish untextured."
}

# ------------------------------------------------------------------ move it
if (Test-Path -LiteralPath $Target) { Remove-Item -LiteralPath $Target -Recurse -Force }
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Target) | Out-Null
if ($Copy) {
    Write-Host "copying (this takes a minute)..."
    Copy-Item -LiteralPath $src -Destination $Target -Recurse
} else {
    Move-Item -LiteralPath $src -Destination $Target
}

# ----------------------------------------------------------- verify in place
# The .mtl files reference sibling packages as ../Package/tex.png, so a move
# only stays valid if the whole tree moved together. Check a sample rather
# than trusting it.
$broken = 0; $checked = 0
foreach ($m in (Get-ChildItem $Target -Recurse -File -Filter *.mtl | Select-Object -First 200)) {
    foreach ($line in (Get-Content $m.FullName)) {
        if ($line -match '^map_\w+\s+(.+)$') {
            $checked++
            $p = Join-Path $m.DirectoryName $Matches[1]
            if (-not (Test-Path -LiteralPath $p)) { $broken++ }
        }
    }
}
Write-Host ("texture refs checked: {0}, broken: {1}" -f $checked, $broken)

$size = (Get-ChildItem $Target -Recurse -File | Measure-Object Length -Sum).Sum / 1GB
$pkgs = @(Get-ChildItem $Target -Directory).Count
Write-Host ("published {0} packages, {1:N2} GB -> {2}" -f $pkgs, $size, $Target)

# Keep it out of git: it is generated, and it is gigabytes.
$gi = Join-Path $repo '.gitignore'
$rel = ($Target.Replace($repo, '').TrimStart('\') -replace '\\', '/')
if ((Get-Content $gi -Raw) -notmatch [regex]::Escape($rel)) {
    Add-Content $gi "`n# Generated by tools/xcom2/xcom_bulk.ps1 - gigabytes, rebuildable, not committed.`n$rel/"
    Write-Host "added '$rel/' to .gitignore"
}
