#!/usr/bin/env python3
"""gen_fa_icons.py - one icon vocabulary for both of cromwell's UIs.

WHY THIS EXISTS. cromwell draws UI two completely unrelated ways: ImGui, which
wants a C++ string constant holding a UTF-8 codepoint, and CEF, which wants a
CSS class whose ::before content is that same codepoint. Hand-maintaining the
two lists is the obvious approach and it is wrong, because nothing catches the
drift: a wrong codepoint is not a compile error and not a script error, it is a
tofu box in one of the two UIs that nobody notices until a screenshot. So both
artefacts come out of one run over one input, and the only way they can
disagree is if somebody edits a generated file by hand.

THE INPUT is Font Awesome's cheatsheet - name, glyph, u+XXXX, families - which
ships with the desktop pack. THE FAMILIES COLUMN IS NOT TRUSTED. Every brand in
it (steam, discord, github, 500px) is tagged "free classic" rather than
"brands", so believing it would put brand glyphs in the solid face, where they
do not exist, and render nothing. Coverage is read from the OTF cmap tables
instead - the fonts are the only authority on what the fonts contain, which is
the same rule the derived-cache tests in this codebase follow.

USAGE
    python tools/gen_fa_icons.py

Reads src/cromwell/assets/fonts/, writes src/cromwell/ui/FontAwesomeIcons.hpp
(committed - it is text, and it is the API every call site spells) and
src/cromwell/assets/web/cromwell_ui.css (not committed - it carries the fonts
themselves, base64'd, and is regenerated by this script).

WHY THE CSS EMBEDS THE FONTS RATHER THAN LINKING THEM. Chromium applies CORS to
@font-face, and a file:// page has an opaque origin, so a stylesheet that names
its fonts by relative path renders every icon as a box under exactly the setup
cromwell uses. Passing --allow-file-access-from-files would fix it and would
also weaken the sandbox for every page the surface ever loads. data: URIs cost
a third more bytes in a generated file nobody reads and need no flag at all.
"""

import base64
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "src" / "cromwell" / "assets" / "fonts"
CHEATSHEET = FONT_DIR / "FontAwesome" / "CHEATSHEET_FULL.txt"
HEADER_OUT = ROOT / "src" / "cromwell" / "ui" / "FontAwesomeIcons.hpp"
CSS_OUT = ROOT / "src" / "cromwell" / "assets" / "web" / "cromwell_ui.css"

# The two icon faces cromwell ships. Order matters: it is the order ImGui merges
# them in, and the first face to claim a codepoint wins, so the solid face - the
# one that carries the whole classic set - goes first.
SOLID = FONT_DIR / "FontAwesome" / "FontAwesome-ProSolid.otf"
BRANDS = FONT_DIR / "FontAwesome" / "FontAwesome-Brands.otf"

# Inter, as the CSS needs it: (file, css weight). Named weights rather than
# letting the browser synthesise - a faux-bold Inter is visibly worse than the
# real one, and we have the real one.
INTER_WEIGHTS = [
    ("Inter-Regular.ttf", 400),
    ("Inter-Medium.ttf", 500),
    ("Inter-SemiBold.ttf", 600),
    ("Inter-Bold.ttf", 700),
    ("Inter-ExtraBold.ttf", 800),
]


# ---------------------------------------------------------------------------
# OTF cmap reading
#
# Enough of the format to answer one question - "does this face contain this
# codepoint" - and no more. Formats 4 and 12 are the only two that matter:
# every font Font Awesome ships uses one or both, 12 for the icons above the
# BMP boundary and 4 for the rest.
# ---------------------------------------------------------------------------

def _read_cmap(path):
    data = path.read_bytes()

    # Table directory. An OTF with CFF outlines starts 'OTTO', a TTF starts
    # 0x00010000; both lay the directory out identically, so neither is checked.
    num_tables = struct.unpack(">H", data[4:6])[0]
    cmap_offset = None
    for i in range(num_tables):
        entry = 12 + i * 16
        tag = data[entry:entry + 4]
        if tag == b"cmap":
            cmap_offset = struct.unpack(">I", data[entry + 8:entry + 12])[0]
            break
    if cmap_offset is None:
        raise ValueError(f"{path.name}: no cmap table")

    num_records = struct.unpack(">H", data[cmap_offset + 2:cmap_offset + 4])[0]
    subtables = []
    for i in range(num_records):
        rec = cmap_offset + 4 + i * 8
        platform, encoding = struct.unpack(">HH", data[rec:rec + 4])
        offset = struct.unpack(">I", data[rec + 4:rec + 8])[0]
        subtables.append((platform, encoding, cmap_offset + offset))

    codepoints = set()
    for platform, encoding, offset in subtables:
        # Windows Unicode only. The Mac Roman subtable maps the same glyphs
        # through a byte encoding and would contribute noise, not coverage.
        if platform != 3 or encoding not in (1, 10):
            continue
        fmt = struct.unpack(">H", data[offset:offset + 2])[0]
        if fmt == 4:
            codepoints |= _read_format4(data, offset)
        elif fmt == 12:
            codepoints |= _read_format12(data, offset)

    if not codepoints:
        raise ValueError(f"{path.name}: cmap had no usable Windows subtable")
    return codepoints


def _read_format4(data, offset):
    seg_x2 = struct.unpack(">H", data[offset + 6:offset + 8])[0]
    segs = seg_x2 // 2

    ends = offset + 14
    starts = ends + seg_x2 + 2          # +2 skips reservedPad
    deltas = starts + seg_x2
    ranges = deltas + seg_x2

    found = set()
    for i in range(segs):
        end = struct.unpack(">H", data[ends + i * 2:ends + i * 2 + 2])[0]
        start = struct.unpack(">H", data[starts + i * 2:starts + i * 2 + 2])[0]
        delta = struct.unpack(">h", data[deltas + i * 2:deltas + i * 2 + 2])[0]
        range_offset = struct.unpack(">H", data[ranges + i * 2:ranges + i * 2 + 2])[0]
        if start == 0xFFFF:
            continue
        for cp in range(start, end + 1):
            if range_offset == 0:
                glyph = (cp + delta) & 0xFFFF
            else:
                addr = ranges + i * 2 + range_offset + (cp - start) * 2
                if addr + 2 > len(data):
                    continue
                glyph = struct.unpack(">H", data[addr:addr + 2])[0]
                if glyph:
                    glyph = (glyph + delta) & 0xFFFF
            if glyph:
                found.add(cp)
    return found


def _read_format12(data, offset):
    num_groups = struct.unpack(">I", data[offset + 12:offset + 16])[0]
    found = set()
    for i in range(num_groups):
        g = offset + 16 + i * 12
        start, end, _glyph = struct.unpack(">III", data[g:g + 12])
        # Guard against a corrupt count claiming a range the size of Unicode.
        if end - start > 0x10000:
            continue
        found.update(range(start, end + 1))
    return found


# ---------------------------------------------------------------------------
# Cheatsheet
# ---------------------------------------------------------------------------

ROW = re.compile(r"^(\S+)\s+.*?u\+([0-9a-fA-F]+)\s")


def read_cheatsheet(path):
    """Yields (icon-name, codepoint). The glyph column between the name and the
    u+ is skipped rather than parsed - it is the literal character, it is a box
    in every editor, and the codepoint beside it says the same thing."""
    icons = []
    seen = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = ROW.match(line)
        if not match:
            continue                      # header prose and blank lines
        name, hex_cp = match.group(1), match.group(2)
        cp = int(hex_cp, 16)
        if name in seen:
            continue
        seen[name] = cp
        icons.append((name, cp))
    return icons


def macro_name(name):
    """steam -> ICON_FA_STEAM, 360-degrees -> ICON_FA_360_DEGREES. The prefix is
    what keeps digit-leading names legal identifiers."""
    return "ICON_FA_" + re.sub(r"[^0-9A-Za-z]", "_", name).upper()


def utf8_escape(cp):
    return "".join(f"\\x{b:02x}" for b in chr(cp).encode("utf-8"))


# ---------------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------------

def write_header(icons, solid_cps, brands_cps):
    lines = []
    lines.append("/* FontAwesomeIcons.hpp - GENERATED by tools/gen_fa_icons.py. Do not edit.")
    lines.append(" *")
    lines.append(" * Font Awesome Pro+ 7.3.1 glyph constants, for both of cromwell's UIs.")
    lines.append(" * ImGui takes these directly - an icon is just text, so ImGui::Text(")
    lines.append(" * ICON_FA_GEAR \" Settings\") is the whole idiom, tinted by the text colour")
    lines.append(" * and sized by the font. CEF takes the CSS this same script emits, whose")
    lines.append(" * class names are the icon names below with an fa- prefix.")
    lines.append(" *")
    lines.append(" * NEVER SPELL A RAW CODEPOINT AT A CALL SITE. \"\\uf013\" is unreviewable and")
    lines.append(" * silently becomes the wrong icon when the pack is updated; ICON_FA_GEAR is")
    lines.append(" * a compile error if it ever stops existing.")
    lines.append(" *")
    lines.append(f" * {len(icons)} icons. ICON_MIN_FA/ICON_MAX_FA bound the glyph range for")
    lines.append(" * ImFontConfig::GlyphRanges - see UiFonts.cpp, the only caller that needs")
    lines.append(" * them.")
    lines.append(" *")
    lines.append(" * THE RANGE DELIBERATELY EXCLUDES ASCII. Both icon faces alias the printable")
    lines.append(" * ASCII block - '0' through '9' and 'A' through 'Z' are icons in their own")
    lines.append(" * right - so a merge range starting at 0x21 would hand every letter and")
    lines.append(" * digit in the UI to Font Awesome and render the whole interface as icons.")
    lines.append(" * ImGui's first-font-wins merge already protects us because Inter is added")
    lines.append(" * first, but relying on that would make the load order silently")
    lines.append(" * load-bearing, and the ASCII glyphs are atlas space for glyphs Inter")
    lines.append(" * already draws better. The macros for those aliases are still emitted")
    lines.append(" * below - they expand to the plain character, which is what a caller")
    lines.append(" * wanting a literal digit wants anyway.")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("")

    covered = [(n, cp) for n, cp in icons if cp in solid_cps or cp in brands_cps]
    pua = [cp for _, cp in covered if cp >= 0xE000]
    lines.append(f"#define ICON_MIN_FA 0x{min(pua):04x}")
    lines.append(f"#define ICON_MAX_FA 0x{max(pua):04x}")
    lines.append("")

    for name, cp in icons:
        if cp not in solid_cps and cp not in brands_cps:
            continue
        face = "brands" if cp in brands_cps and cp not in solid_cps else "solid"
        note = face if cp >= 0xE000 else f"{face}, ascii alias"
        lines.append(f'#define {macro_name(name)} "{utf8_escape(cp)}"\t// U+{cp:04x} {note}')

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    HEADER_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(covered)


def data_uri(path, mime):
    return f"data:{mime};base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def write_css(icons, solid_cps, brands_cps):
    out = []
    out.append("/* cromwell_ui.css - GENERATED by tools/gen_fa_icons.py. Do not edit.")
    out.append(" *")
    out.append(" * The web half of cromwell's UI typography: Inter as the page font and")
    out.append(" * Font Awesome as .fa-<name> classes, matching FontAwesomeIcons.hpp glyph")
    out.append(" * for glyph because one script emits both.")
    out.append(" *")
    out.append(" * The fonts are embedded as data: URIs, not linked. Chromium enforces CORS")
    out.append(" * on @font-face and a file:// page has an opaque origin, so a relative")
    out.append(" * src: url() renders every glyph as a box in exactly the configuration")
    out.append(" * WebSurface uses.")
    out.append(" */")
    out.append("")

    for filename, weight in INTER_WEIGHTS:
        uri = data_uri(FONT_DIR / "Inter" / filename, "font/ttf")
        out.append("@font-face {")
        out.append('  font-family: "Inter";')
        out.append("  font-style: normal;")
        out.append(f"  font-weight: {weight};")
        out.append("  font-display: block;")
        out.append(f'  src: url("{uri}") format("truetype");')
        out.append("}")
        out.append("")

    for family, path in (("Font Awesome Solid", SOLID), ("Font Awesome Brands", BRANDS)):
        uri = data_uri(path, "font/otf")
        out.append("@font-face {")
        out.append(f'  font-family: "{family}";')
        out.append("  font-style: normal;")
        out.append("  font-weight: 900;")
        out.append("  font-display: block;")
        out.append(f'  src: url("{uri}") format("opentype");')
        out.append("}")
        out.append("")

    # Inter needs no fallback stack worth the name - it is embedded, so it either
    # loaded or the stylesheet did not, and a system-font fallback would only
    # disguise the second case.
    out.append(":root { --cw-font-ui: \"Inter\", sans-serif; }")
    out.append("html, body { font-family: var(--cw-font-ui); }")
    out.append("")
    out.append("/* Icons are inline text, so they inherit colour and scale with font-size.")
    out.append("   line-height 1 keeps a glyph from stretching the line box it sits in. */")
    out.append(".fa, .fa-brand {")
    out.append("  display: inline-block;")
    out.append("  font-style: normal;")
    out.append("  font-weight: 900;")
    out.append("  font-variant: normal;")
    out.append("  line-height: 1;")
    out.append("  text-rendering: auto;")
    out.append("  -webkit-font-smoothing: antialiased;")
    out.append("}")
    out.append('.fa { font-family: "Font Awesome Solid"; }')
    out.append('.fa-brand { font-family: "Font Awesome Brands"; }')
    out.append("")

    count = 0
    for name, cp in icons:
        if cp not in solid_cps and cp not in brands_cps:
            continue
        out.append(f'.fa-{name}::before {{ content: "\\{cp:x}"; }}')
        count += 1

    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    return count


def main():
    for required in (CHEATSHEET, SOLID, BRANDS):
        if not required.exists():
            print(f"missing: {required}", file=sys.stderr)
            print("The licensed font pack is not in git - see "
                  "src/cromwell/assets/fonts/README.md.", file=sys.stderr)
            return 1

    icons = read_cheatsheet(CHEATSHEET)
    solid_cps = _read_cmap(SOLID)
    brands_cps = _read_cmap(BRANDS)

    # Collisions would make the merge order load-bearing and the two UIs
    # disagree, since CSS picks a face by class and ImGui picks by merge order.
    named = {cp for _, cp in icons}
    overlap = (solid_cps & brands_cps) & named
    if overlap:
        print(f"warning: {len(overlap)} codepoints in both faces; solid wins",
              file=sys.stderr)

    missing = [n for n, cp in icons
               if cp not in solid_cps and cp not in brands_cps]

    header_count = write_header(icons, solid_cps, brands_cps)
    css_count = write_css(icons, solid_cps, brands_cps)
    assert header_count == css_count, "header and CSS disagree on icon count"

    print(f"{len(icons)} icons in cheatsheet, {header_count} covered by the "
          f"shipped faces ({len(missing)} in Pro faces we do not ship)")
    print(f"  {HEADER_OUT.relative_to(ROOT)}")
    print(f"  {CSS_OUT.relative_to(ROOT)}  "
          f"({CSS_OUT.stat().st_size / 1024 / 1024:.1f} MB, fonts embedded)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
